[package]
name = "jogo_adivinhacao"
version = "0.1.0"
edition = "2021"
authors = ["Lucas Lima Fernandes <lucas.lfernandes@live.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"
